### ISSUE TITLE
add via stops feature

### ISSUE THREAD

**Issue by lennartgrunau** [jeyemwey/train-ics-converter#9]
I've booked some tickets/ trips that are custom plannend and not directly recommended by DB and thus, this tool doesn't recommend them either. 
Hence, a stopover feature would be nice.

**Comment by jeyemwey** [comment]
Should be possible. There is a `via` option in the [`journeys` request](https://github.com/public-transport/hafas-client/blob/master/docs/journeys.md#journeysfrom-to-opt), but I'm not sure what kind of data they need.

Also, I'm not sure about the UX, but thats for a later point.

**Comment by jeyemwey** [comment]
Work in progress has been made.

Backend request without a via stop:
![image](https://user-images.githubusercontent.com/2796271/140662045-6f26a9a3-a41b-4a25-88de-ba7c9755e9c2.png)

Backend-Request with a via stop:
![image](https://user-images.githubusercontent.com/2796271/140662060-c0c9c9a7-b8eb-40b2-8295-c6904f5ba93b.png)

I'll try to add a frontend change tomorrow, so this can be resolved $soonish.

**Comment by jeyemwey** [comment]
Added feature with 4488c5a6b1803cc5dc2c1031d6cf4fd5e8813ea1 and deployed via CI. Please check out https://train-ics.ipv4.rocks/ for the new version.

**Comment by lennartgrunau** [comment]
Big fan, much appreciated.
